name: CI

on:
  push:
    branches: ['build']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VITE_RAPID_API_KEY=${{ secrets.VITE_RAPID_API_KEY }}
            VITE_CURRENT_WEATHER_API_KEY=${{ secrets.VITE_CURRENT_WEATHER_API_KEY }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APPNAME }}:${{ steps.package-version.outputs.current-version}}
